version: '3'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2017-CU8-ubuntu
    volumes:
      - datafiles:/var/opt/mssql/data
    ports:
      - "1433:1433"
    restart: always
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: SqlExpress$$

  studentapi:
    build:
      context: ./StudentApi
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "5000:80"
      - "5001:443"
    restart: always
    environment:
       - DBHOST=db
       - DBPORT=1433
       - DBPASSWORD=SqlExpress$$
       - ASPNETCORE_ENVIRONMENT=Development

  blazorapp:
    image: blazorapp
    build:
      context: ./Assignment2
      dockerfile: Dockerfile
    ports:
      - 8888:80
volumes:
  datafiles: