// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentApi.Data;

namespace StudentApi.Data.Migrations
{
    [DbContext(typeof(StudentDbContext))]
    partial class StudentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StudentLibrary.Student", b =>
                {
                    b.Property<string>("BcitId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BcitId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            BcitId = "A00123456",
                            City = "Chilliwack",
                            EmailAddress = "jim@potter.com",
                            FirstName = "Jim",
                            LastName = "Potter",
                            MobileNumber = "604-123-4567",
                            Specialization = "Nursing"
                        },
                        new
                        {
                            BcitId = "A00000001",
                            City = "Vancouver",
                            EmailAddress = "jdouglas@bcit.ca",
                            FirstName = "Jane",
                            LastName = "Douglas",
                            MobileNumber = "778-123-4567",
                            Specialization = "Business"
                        },
                        new
                        {
                            BcitId = "A00000002",
                            City = "Burnaby",
                            EmailAddress = "tgardner@bcit.ca",
                            FirstName = "Tom",
                            LastName = "Gardner",
                            MobileNumber = "604-999-0123",
                            Specialization = "Education"
                        },
                        new
                        {
                            BcitId = "A00000003",
                            City = "Burnaby",
                            EmailAddress = "alee@bcit.ca",
                            FirstName = "Ann",
                            LastName = "Lee",
                            MobileNumber = "778-999-0123",
                            Specialization = "Biology"
                        },
                        new
                        {
                            BcitId = "A00000004",
                            City = "Richmond",
                            EmailAddress = "jjones@bcit.ca",
                            FirstName = "James",
                            LastName = "Jones",
                            MobileNumber = "604-765-4321",
                            Specialization = "Radiology"
                        },
                        new
                        {
                            BcitId = "A00000005",
                            City = "Coquitlam",
                            EmailAddress = "staylor@bcit.ca",
                            FirstName = "Susan",
                            LastName = "Taylor",
                            MobileNumber = "778-765-4321",
                            Specialization = "Math"
                        },
                        new
                        {
                            BcitId = "A01234567",
                            City = "Delta",
                            EmailAddress = "pwhite@bcit.ca",
                            FirstName = "Peter",
                            LastName = "White",
                            MobileNumber = "604-012-3456",
                            Specialization = "Administration"
                        },
                        new
                        {
                            BcitId = "A07654321",
                            City = "Richmond",
                            EmailAddress = "pfox@bcit.ca",
                            FirstName = "Philip",
                            LastName = "Fox",
                            MobileNumber = "778-012-3456",
                            Specialization = "Computer Science"
                        },
                        new
                        {
                            BcitId = "A12345678",
                            City = "Vancouver",
                            EmailAddress = "dray@bcit.ca",
                            FirstName = "Donna",
                            LastName = "Ray",
                            MobileNumber = "604-999-9999",
                            Specialization = "Chemistry"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
