version: '3'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2017-CU8-ubuntu
    volumes:
      - datafiles:/var/opt/mssql/data
    ports:
      - "1433:1433"
    restart: always
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: SqlExpress$$

  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "6000:80"
      - "6001:443"
    restart: always
    environment:
      - DBHOST=db
      - DBPORT=1433
      - DBPASSWORD=SqlExpress$$
      - ASPNETCORE_ENVIRONMENT=Development
volumes:
  datafiles: